:concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] || 10 %>
:logfile: log/sidekiq.log
:queues:
  - critical
  - high
  - default
  - mailers
  - chewy
  - low
:limits:
  low: 1
:scheduler:
  :schedule:
    send_goal_deadline_reminder:
      cron: "0 12 L * *" # Runs on the last day of the month at 12:00
      class: EmailReminders::SendGoalDeadlineReminderJob
    send_goal_due_in_one_month_reminder_job:
      cron: "0 12 * * *" # Runs once every day at 12:00
      class: EmailReminders::SendGoalDueInOneMonthReminderJob
    send_goal_15_days_past_due_date_reminder_job:
      cron: "0 12 * * *" # Runs once every day at 12:00
      class: EmailReminders::SendGoal15DaysPastDueDateReminderJob
    send_goal_30_days_past_due_date_reminder_job:
      cron: "0 12 * * *" # Runs once every day at 12:00
      class: EmailReminders::SendGoal30DaysPastDueDateReminderJob
    sync_on_chain_talent_supporters:
      cron: "0 * * * *" # Runs every hour
      class: TriggerTalentSupportersRefreshJob
      enabled: <%= ENV["ENABLE_THE_GRAPH_JOBS"] %>
    send_token_launch_reminder:
      cron: "0 10 * * *" # Runs once every day at 10am
      class: EmailReminders::SendTokenLaunchReminderJob
      enabled: <%= ENV["EMAIL_REMINDER_DAYS"].to_i > 0 %>
    send_token_purchase_reminder:
      cron: "0 10 * * *" # Runs once every day at 10am
      class: EmailReminders::SendTokenPurchaseReminderJob
      enabled: <%= ENV["EMAIL_REMINDER_DAYS"].to_i > 0 %>
    send_complete_profile_reminder:
      cron: "0 10 * * *" # runs once every day at 10am
      class: EmailReminders::SendCompleteProfileReminderJob
      enabled: <%= ENV["EMAIL_REMINDER_DAYS"].to_i > 0 %>
    daily_metrics:
      cron: "1 0 * * *" # runs once every day at 8am
      class: DailyMetricsJob
    sync_with_persona_job:
      cron: "0 * * * *" # Runs every hour
      class: SyncWithPersonaJob
    update_chewy_index:
      cron: "0 * * * *" # Runs every hour
      class: TriggerChewyIndexUpdateJob
    refresh_quests_job:
      cron: "0 13 * * *" # Runs once every day at 13:00
      class: Quests::RefreshQuestsJob
    refresh_talent_mate_quests_job:
      cron: "0 14 * * *" # Runs once every day at 14:00
      class: Quests::RefreshTalentMateQuestsJob
