:concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] || 10 %>
:logfile: log/sidekiq.log
:queues:
  - critical
  - high
  - default
  - mailers
  - low
:limits:
  low: 1
:schedule:
  send_career_need_opportunity_emails:
    cron: "0 11 * * *" # runs once every day at 11:00
    class: SendCareerNeedOpportunityEmailsJob
  send_goal_deadline_reminder:
    cron: "0 12 L * *" # Runs on the last day of the month at 12:00
    class: EmailReminders::SendGoalDeadlineReminderJob
  send_goal_halfway_reminder:
    cron: "0 12 * * *" # Runs once every day at 12:00
    class: EmailReminders::SendGoalHalfwayReminderJob
  send_notification_digests:
    cron: "0 10 * * *" # runs once every day at 10am
    class: SendNotificationDigestsJob
  sync_talent_with_notion:
    cron: "0 20 * * *" # Runs once every day at 8pm
    class: SyncTalentWithNotionJob
  sync_on_chain_talent_supporters:
    cron: "0 * * * *" # Runs every hour
    class: TriggerTalentSupportersRefreshJob
    enabled: <%= ENV["ENABLE_THE_GRAPH_JOBS"] %>
  send_token_launch_reminder:
    cron: "0 10 * * *" # Runs once every day at 10am
    class: EmailReminders::SendTokenLaunchReminderJob
    enabled: <%= ENV["EMAIL_REMINDER_DAYS"].to_i > 0 %>
  send_token_purchase_reminder:
    cron: "0 10 * * *" # Runs once every day at 10am
    class: EmailReminders::SendTokenPurchaseReminderJob
    enabled: <%= ENV["EMAIL_REMINDER_DAYS"].to_i > 0 %>
  send_complete_profile_reminder:
    cron: "0 10 * * *" # runs once every day at 10am
    class: EmailReminders::SendCompleteProfileReminderJob
    enabled: <%= ENV["EMAIL_REMINDER_DAYS"].to_i > 0 %>
  send_digest_email:
    cron: "0 8 * * *" # runs once every day at 8am
    class: EmailReminders::SendDigestEmailJob
    enabled: <%= ENV["DIGEST_EMAIL_DAYS"].to_i > 0 %>
  daily_metrics:
    cron: "1 0 * * *" # runs once every day at 8am
    class: DailyMetricsJob
  setup_next_race:
    cron: "1 0 1 * *" # Runs every month at 00:01
    class: SetupNextRaceJob
  sync_with_persona_job:
    cron: "0 * * * *" # Runs every hour
    class: SyncWithPersonaJob
  update_chewy_index:
    cron: "0 * * * *" # Runs every hour
    class: TriggerChewyIndexUpdateJob
